# Generated by Django 3.0 on 2020-10-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_bookitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='total_checkedout',
            field=models.IntegerField(default=0),
        ),
    ]
