# Generated by Django 3.0 on 2020-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_bookitem_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
