# Generated by Django 3.0 on 2020-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.TextField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=250, null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
