# Generated by Django 3.0 on 2020-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_bookitem_total_checkedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='renewal',
            field=models.IntegerField(default=0),
        ),
    ]
