# Generated by Django 3.0 on 2020-10-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20201013_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='message',
            new_name='display_message',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='material_type',
            field=models.CharField(default='book', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='location',
            field=models.CharField(choices=[('1/F', '1/F'), ('2/F', '2/F'), ('3/F', '3/F'), ('1/F Reference', '1/F Reference')], max_length=25),
        ),
    ]
